-- Part 1/4: run first (includes delete)
delete from public.restaurants
where city in ('houston', 'cypress')
  and owner_id is null;

insert into public.restaurants (
  owner_id, name, description, location, cuisine_type, image_url,
  capacity, is_featured, display_rank, tags, price_level, event_types,
  latitude, longitude, city, status, is_visible, subscription_status
) values
(
  null,
  'Killen''s Steakhouse',
  'Wood-fired steaks and Gulf seafood in Pearland—power lunches and celebration dinners with private dining coordination.',
  'Pearland, Houston metro',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  140,
  true,
  1,
  array['luxury', 'corporate', 'private-dining-focused'],
  4,
  array['corporate', 'dinner', 'birthday'],
  29.554,
  -95.392,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Pappas Bros. Steakhouse',
  'Houston''s benchmark for dry-aged beef, extensive wine, and boardroom-ready private rooms downtown.',
  'Galleria / Uptown, Houston',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  160,
  true,
  2,
  array['luxury', 'corporate', 'private-dining-focused'],
  4,
  array['corporate', 'dinner'],
  29.74,
  -95.462,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Vic & Anthony''s Steakhouse',
  'Classic steakhouse elegance inside the Golden Nugget—ideal for client entertainment and milestone birthdays.',
  'Downtown Houston',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  120,
  false,
  0,
  array['luxury', 'corporate'],
  4,
  array['corporate', 'dinner', 'birthday'],
  29.763,
  -95.364,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Brenner''s Steakhouse on the Bayou',
  'River Oaks institution with bayou views, prime cuts, and semi-private rooms for executive gatherings.',
  'River Oaks, Houston',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  100,
  false,
  0,
  array['luxury', 'romantic', 'private-dining-focused'],
  4,
  array['date_night', 'corporate', 'dinner'],
  29.752,
  -95.418,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Tony''s',
  'White-tablecloth Italian-American fine dining—holiday parties, rehearsal dinners, and VIP hospitality.',
  'Greenway Plaza, Houston',
  'Italian',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
  90,
  false,
  0,
  array['luxury', 'private-dining-focused'],
  4,
  array['corporate', 'dinner', 'birthday'],
  29.731,
  -95.434,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Davis Street at Hermann Park',
  'Seasonal American from a veteran chef team—corporate buyouts and chef''s table experiences.',
  'Museum District, Houston',
  'Modern American',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
  85,
  false,
  0,
  array['luxury', 'corporate'],
  4,
  array['corporate', 'dinner'],
  29.722,
  -95.389,
  'houston',
  'active',
  true,
  'none'),
(null,
  'March',
  'Mediterranean fine dining with a wine program built for hosted tastings and intimate celebrations.',
  'Montrose, Houston',
  'Mediterranean',
  'https://images.unsplash.com/photo-1510812431401-41d2bd2724f3?w=800&q=80',
  70,
  false,
  0,
  array['luxury', 'romantic'],
  4,
  array['date_night', 'dinner', 'birthday'],
  29.742,
  -95.402,
  'houston',
  'active',
  true,
  'none'),
(null,
  'The Annie Café & Bar',
  'Polished café-by-day, dinner destination by night—rooftop-adjacent energy for upscale social events.',
  'Galleria, Houston',
  'Modern American',
  'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80',
  110,
  false,
  0,
  array['luxury', 'nightlife'],
  4,
  array['party', 'corporate', 'dinner'],
  29.738,
  -95.461,
  'houston',
  'active',
  true,
  'none'),
(null,
  'La Griglia',
  'See-and-be-seen Italian steakhouse on West Gray—birthdays, engagements, and high-energy group dinners.',
  'River Oaks, Houston',
  'Italian',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
  130,
  false,
  0,
  array['luxury', 'nightlife', 'loud'],
  4,
  array['birthday', 'party', 'dinner'],
  29.748,
  -95.41,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Masraff''s',
  'Upscale American with a loyal Uptown crowd—reliable for corporate anniversaries and client dinners.',
  'Uptown, Houston',
  'Modern American',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
  95,
  false,
  0,
  array['luxury', 'corporate'],
  4,
  array['corporate', 'dinner'],
  29.745,
  -95.456,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Eddie V''s Prime Seafood',
  'Live jazz, prime seafood, and private dining for financial district entertainment.',
  'River Oaks, Houston',
  'Seafood',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
  150,
  true,
  3,
  array['luxury', 'corporate', 'nightlife'],
  4,
  array['corporate', 'date_night', 'dinner'],
  29.754,
  -95.415,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Truluck''s Ocean''s Finest',
  'Stone crab, lobster, and piano bar atmosphere—popular for hosted client appreciation nights.',
  'Westheimer, Houston',
  'Seafood',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
  120,
  false,
  0,
  array['luxury', 'corporate'],
  4,
  array['corporate', 'dinner'],
  29.741,
  -95.478,
  'houston',
  'active',
  true,
  'none'),
(null,
  'State of Grace',
  'Gulf seafood and wood-fired steaks in a grand dining room—large-format celebrations welcome.',
  'Tanglewood, Houston',
  'Seafood',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80',
  180,
  false,
  0,
  array['luxury', 'family-friendly', 'corporate'],
  4,
  array['birthday', 'corporate', 'dinner'],
  29.768,
  -95.489,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Xochi',
  'Oaxacan-inspired James Beard spotlight—tasting menus and buyouts for discerning food-forward groups.',
  'Downtown Houston',
  'Mexican',
  'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80',
  75,
  false,
  0,
  array['luxury'],
  4,
  array['dinner', 'birthday'],
  29.76,
  -95.362,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Spindletop Restaurant',
  'Revolving rooftop views atop the Hyatt—iconic skyline dinners and cocktail receptions.',
  'Downtown Houston',
  'Modern American',
  'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80',
  200,
  true,
  4,
  array['luxury', 'romantic', 'corporate'],
  4,
  array['corporate', 'date_night', 'party'],
  29.758,
  -95.365,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Z on 23 Rooftop',
  'Pool deck dining with downtown panoramas—launch parties and sunset corporate mixers.',
  'Downtown Houston',
  'Contemporary',
  'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80',
  180,
  false,
  0,
  array['luxury', 'nightlife'],
  4,
  array['party', 'corporate'],
  29.755,
  -95.368,
  'houston',
  'active',
  true,
  'none'),
(null,
  'B&B Butchers & Restaurant',
  'Steakhouse meets butcher shop—trophy room vibes for team wins and executive dinners.',
  'Washington Ave, Houston',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  160,
  false,
  0,
  array['luxury', 'loud', 'corporate'],
  4,
  array['corporate', 'party', 'dinner'],
  29.77,
  -95.408,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Del Frisco''s Double Eagle',
  'Two-story steakhouse with wine vault—favored for holiday parties and large guest counts.',
  'Galleria, Houston',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  220,
  false,
  0,
  array['luxury', 'corporate', 'private-dining-focused'],
  4,
  array['corporate', 'birthday', 'dinner'],
  29.737,
  -95.464,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Fleming''s Prime Steakhouse',
  'Consistent national luxury with private wine dinners—safe pick for corporate roadshows.',
  'Uptown, Houston',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  140,
  false,
  0,
  array['luxury', 'corporate'],
  4,
  array['corporate', 'dinner'],
  29.744,
  -95.458,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Ruth''s Chris Steak House',
  'Sizzling plates and private rooms—banking and energy sector entertainment staple.',
  'Galleria, Houston',
  'Steakhouse',
  'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80',
  150,
  false,
  0,
  array['luxury', 'corporate'],
  4,
  array['corporate', 'dinner'],
  29.739,
  -95.46,
  'houston',
  'active',
  true,
  'none'),
(null,
  'The Pit Room',
  'Central Texas-style brisket and ribs—casual corporate offsites with catering trays.',
  'Montrose, Houston',
  'BBQ',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  90,
  false,
  0,
  array['casual', 'corporate'],
  2,
  array['corporate', 'party', 'dinner'],
  29.743,
  -95.398,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Blood Bros BBQ',
  'Houston Chronicle darling—bold flavors for team lunches and brewery-adjacent parties.',
  'East Downtown, Houston',
  'BBQ',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  70,
  false,
  0,
  array['casual', 'loud'],
  2,
  array['party', 'birthday'],
  29.748,
  -95.352,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Fainmoss BBQ',
  'Neighborhood smokehouse with picnic-table energy—family reunions and casual celebrations.',
  'Third Ward, Houston',
  'BBQ',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  60,
  false,
  0,
  array['casual', 'family-friendly'],
  2,
  array['birthday', 'party'],
  29.728,
  -95.355,
  'houston',
  'active',
  true,
  'none'),
(null,
  'CorkScrew BBQ',
  'Spring-area legend worth the drive—whole-hog feasts and corporate picnic packages.',
  'Spring, Houston metro',
  'BBQ',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  100,
  false,
  0,
  array['casual', 'family-friendly', 'corporate'],
  2,
  array['corporate', 'party'],
  30.079,
  -95.417,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Pitmaster BBQ',
  'East End smoke with daily specials—budget-friendly team outings.',
  'East End, Houston',
  'BBQ',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  55,
  false,
  0,
  array['casual'],
  1,
  array['party', 'dinner'],
  29.735,
  -95.328,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Ray''s BBQ Shack',
  'Third-generation pit—soulful Houston BBQ for community fundraisers and family events.',
  'Southwest Houston',
  'BBQ',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  65,
  false,
  0,
  array['casual', 'family-friendly'],
  2,
  array['birthday', 'party'],
  29.688,
  -95.458,
  'houston',
  'active',
  true,
  'none'),
(null,
  'Hinze''s Bar-B-Q',
  'Wharton County heritage near the city—smoked meats for rehearsal dinners and reunions.',
  'Wharton, Houston metro',
  'BBQ',
  'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
  80,
  false,
  0,
  array['casual', 'family-friendly'],
  2,
  array['birthday', 'party'],
  29.311,
  -96.095,
  'houston',
  'active',
  true,
  'none');
